###

# curl -X POST http://localhost:3000/trigger-event
#     -H "Content-Type: application/json"
#     -d '{"message": "Isak vant"}'
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "Steffen",
  "email": "isak@gmail.com"
}

###

