###

# curl -X POST http://localhost:3000/trigger-event
#     -H "Content-Type: application/json"
#     -d '{"message": "Isak vant"}'
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "Steffen",
  "email": "isak@gmail.com"
}
###
###

POST http://localhost:3000/users/signup/many
Content-Type: application/json

{
  "users": [
    {
      "name": "Steffen",
      "email": "steffen@braten.no"
    },
    {
      "name": "Kristoffer",
      "email": "kristoffer@hakonsen.no"
    },
    {
      "name": "Geir Olav",
      "email": "geir@olav.no"
    }
  ]
}

###

