###

# curl -X POST http://localhost:3000/trigger-event
#     -H "Content-Type: application/json"
#     -d '{"duelResult": "Isak vant"}'
POST http://localhost:3000/events/all
Content-Type: application/json

{
  "duelResult": "Lupus vant"
}

###

###

# curl -X POST http://localhost:3000/trigger-event
#     -H "Content-Type: application/json"
#     -d '{"duelResult": "Isak vant"}'
POST http://localhost:3000/events
Content-Type: application/json

{
  "duelResult": "Sirius vant",
  "clientId": 1
}

###