###

# curl -X POST http://localhost:3000/trigger-event
#     -H "Content-Type: application/json"
#     -d '{"message": "Isak vant"}'
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "isakbjugn@gmail.com",
  "password": "indiajujube-15"
}

###

